# ANN

### Data Exploration--Intuition

In [1]:
# installed Keras, tensorflow, and theano. 

## Read the data. 

import numpy as np
import pandas as pd
import seaborn as sns
from IPython.display import display


data=pd.read_csv('Churn_Modelling.csv')
labels=data['Exited']
features=data.drop(['RowNumber','CustomerId','Surname','Exited'],axis = 1)
print ("Churning Customers dataset has {} samples with {} features each.".format(*features.shape))
display(features.head(n=1))
display(labels.head(3))
display(data.head(n=3))

Churning Customers dataset has 10000 samples with 10 features each.


CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          619    France  Female   42       2      0.0              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88

0    1
1    0
2    1
Name: Exited, dtype: int64

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [2]:
display(features.describe())
churned_customers=data.loc[labels==0]

print("Total number of Cusomers Who have left the bank: {}".format(len(churned_customers)))

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary  
count  10000.00000    10000.000000     10000.000000  
mean       0.70550        0.515100    100090.239881  
std        0.45584        0.499797     57510.492818  
min        0.00000        0.000000        11.580000  
25%        0.00000        0.000000     51002.110000  
50%        1.00000        1.000000    100193.915000  
75%        1.00000        1.000000    149388.247500  
max        1.00000        1.000000    199992.480000

Total number of Cusomers Who have left the bank: 7963


### Dealing with Categorical Variables. 

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
features_cat=features.select_dtypes(include=['object'])
features['Geography']=labelencoder_X_1.fit_transform(features_cat['Geography'])
display(features.head())



             
             

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [4]:
labelencoder_X_2 = LabelEncoder()
features['Gender']=labelencoder_X_2.fit_transform(features_cat['Gender'])
display(features.head())

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [5]:
onehotencoder = OneHotEncoder(categorical_features = [1])
features = onehotencoder.fit_transform(features).toarray()
display(features[:5,:])
features=features[:,1:]

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          6.19000000e+02,   0.00000000e+00,   4.20000000e+01,
          2.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          6.08000000e+02,   0.00000000e+00,   4.10000000e+01,
          1.00000000e+00,   8.38078600e+04,   1.00000000e+00,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          5.02000000e+02,   0.00000000e+00,   4.20000000e+01,
          8.00000000e+00,   1.59660800e+05,   3.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          6.99000000e+02,   0.00000000e+00,   3.90000000e+01,
          1.00000000e+00,   0.00000000e+00,   2.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   9.38266300e+04],
    

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.2, random_state = 42)

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Neural Netork Build

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

classifier.add(Dense(activation="relu",input_dim=11, units=6, kernel_initializer="uniform"))
classifier.add(Dense(activation="relu",units=6, kernel_initializer="uniform"))
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

y_pred=classifier.predict(X_test)







C:\Users\Phanindra\Anaconda2\envs\py35\lib\site-packages\keras\models.py:826: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 1s - loss: 0.4851 - acc: 0.7941     
Epoch 2/100
8000/8000 [==============================] - 1s - loss: 0.4278 - acc: 0.7990     
Epoch 3/100
8000/8000 [==============================] - 1s - loss: 0.4195 - acc: 0.8230     
Epoch 4/100
8000/8000 [==============================] - 2s - loss: 0.4132 - acc: 0.8320     
Epoch 5/100
8000/8000 [==============================] - 2s - loss: 0.4105 - acc: 0.8336     
Epoch 6/100
8000/8000 [==============================] - 2s - loss: 0.4077 - acc: 0.8337     
Epoch 7/100
8000/8000 [==============================] - 1s - loss: 0.4058 - acc: 0.8331     
Epoch 8/100
8000/8000 [==============================] - 1s - loss: 0.4045 - acc: 0.8346     
Epoch 9/100
8000/8000 [==============================] - 1s - loss: 0.4032 - acc: 0.8352     
Epoch 10/100
8000/8000 [==============================] - 1s - loss: 0.4019 - acc: 0.8357     
Epoch 11/100
8000/8000 [==============================] - 1

8000/8000 [==============================] - 0s - loss: 0.3536 - acc: 0.8585     - ETA: 0s - loss: 0.3410 - 
Epoch 85/100
8000/8000 [==============================] - 0s - loss: 0.3526 - acc: 0.8599     
Epoch 86/100
8000/8000 [==============================] - 0s - loss: 0.3516 - acc: 0.8590     
Epoch 87/100
8000/8000 [==============================] - 0s - loss: 0.3516 - acc: 0.8597     
Epoch 88/100
8000/8000 [==============================] - 0s - loss: 0.3508 - acc: 0.8592     
Epoch 89/100
8000/8000 [==============================] - 0s - loss: 0.3495 - acc: 0.8589     
Epoch 90/100
8000/8000 [==============================] - 0s - loss: 0.3496 - acc: 0.8604     
Epoch 91/100
8000/8000 [==============================] - 0s - loss: 0.3487 - acc: 0.8629     
Epoch 92/100
8000/8000 [==============================] - 0s - loss: 0.3479 - acc: 0.8609     
Epoch 93/100
8000/8000 [==============================] - 0s - loss: 0.3487 - acc: 0.8620     - ETA: 0s - loss: 0.3509 
Epoch 94/10

In [12]:
display(y_pred)

array([[ 0.03811288],
       [ 0.02339289],
       [ 0.11817623],
       ..., 
       [ 0.68704754],
       [ 0.08233839],
       [ 0.30160698]], dtype=float32)

### Thresold-- Predictions

In [17]:
y_pred=(y_pred>0.5)
display(y_pred[10:20])

array([[ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]], dtype=bool)

### Confusion Matrix


In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
display(cm)

array([[1548,   59],
       [ 212,  181]])

In [24]:
print((1548+181)/(2000))

0.8645


## Consumer Data: - Sample
"""Predicting if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""

In [29]:
# Importing the dataset
sample=np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
sc.transform(sample)
sample_pred=classifier.predict(sample)
display(sample_pred>0.5)

array([[False]], dtype=bool)